package imageboard

import (
	"fmt"
	"log"
	"os"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/jmoiron/sqlx"
)

type Thread struct {
	Thread_id int
	Title     string `form:"title"`
	Comment   string `form:"comment"`
	Time      string `db:"to_char"`
}

type Reply struct {
	Reply_id  int
	Thread_id int
	Comment   string `form:"comment"`
	Time      string `db:"to_char"`
}

func ConnectToDB() *sqlx.DB {
	return sqlx.MustConnect("pgx", os.Getenv("DATABASE_URL"))
}

func InitSchema(db *sqlx.DB) {
	schema := `CREATE TABLE threads (
            thread_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            image varchar(255),
            title varchar(50),
            comment varchar(500),
            time timestamp
        );
        CREATE TABLE replies(
            reply_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            thread_id integer REFERENCES threads(thread_id),
            image varchar(255),
            comment varchar(500),
            time timestamp
        );`

	db.MustExec(schema)
}

func CreateThread(db *sqlx.DB, thread Thread) {
	cmd := `INSERT INTO threads(title, comment, time) VALUES ($1,$2, CURRENT_TIMESTAMP)`
	res, err := db.Exec(cmd, thread.Title, thread.Comment)
	_ = res
	if err != nil {
		log.Println(err.Error())
	}
}

func CreateReply(db *sqlx.DB, reply Reply) {
	cmd := `INSERT INTO replies(thread_id, comment, time) VALUES ($1, $2, CURRENT_TIMESTAMP)`
	res, err := db.Exec(cmd, reply.Thread_id, reply.Comment)
	_ = res
	if err != nil {
		log.Println(err)
	}
}

func queryAllThreads(db *sqlx.DB) ([]Thread, error) {
	threads := []Thread{}
	err := db.Select(&threads, `SELECT thread_id, title, comment, to_char(time, 'DD/MM/YYYY HH24:MI:SS') FROM threads`)
	if err != nil {
		fmt.Println(err)
		return threads, err
	}
	return threads, nil
}

func queryThread(db *sqlx.DB, thread_id int64) (Thread, error) {
	thread := Thread{}
	err := db.Get(&thread, `SELECT thread_id,title,comment,to_char(time, 'DD/MM/YYYY HH24:MI:SS') FROM threads WHERE thread_id=$1`, thread_id)
	if err != nil {
		return thread, err
	}
	return thread, nil
}

func queryThreadReplies(db *sqlx.DB, thread_id int) ([]Reply, error) {
	replies := []Reply{}
	rows, err := db.Queryx(`SELECT comment, to_char(time, 'DD/MM/YYYY HH24:MI:SS') FROM replies WHERE thread_id=$1`, thread_id)
	if err != nil {
		log.Println(err)
	}
	for rows.Next() {
		reply := Reply{}
		err := rows.StructScan(&reply)
		if err != nil {
			return replies, err
		}
		replies = append(replies, reply)
	}
	return replies, nil
}
